In [1]:
# int,boolean, string---  are immutable

In [2]:
# Can not reassign 
t= "Tutorialspoint"
print type(t)
t[0] = "M"

SyntaxError: invalid syntax (Temp/ipykernel_3020/20083333.py, line 3)

In [5]:
x = 'banana'
for idx in range (0,5):
    print(x[idx], "=", id(x[idx]))

b = 2397615953328
a = 2397616261488
n = 2397616113840
a = 2397616261488
n = 2397616113840


Numpy--Library python numbers(if u want to put img use numpy),bcz list is low
y is list slo--list use general info only
deep learning,neural network --computation intensive


In [6]:
#types of array-- 1d, 2d,3d arrays are there.(d- dimension)

In [10]:
#how to import num
import numpy as nppy
#1D array


In [9]:
#create an array with list


In [18]:
l1=[11,12,13,14]

In [19]:
n1=np.array(l1)

In [21]:
n1


numpy.ndarray

In [22]:
type(n1) #shows the type of the array( type is the numpy arraynumpy array)

numpy.ndarray

In [23]:
n1.shape #shows the column of the element ( it showing 4 because it is one dimensional array)

(4,)

In [25]:
n1.ndim 

1

In [26]:
n1.itemsize #item size of an element or a particular element

4

In [27]:
n1.dtype 

dtype('int32')

#Access id array
1.n1[index]
2.n1[slice]
3.n1[vector]

In [29]:
n1[-1] #it will give you last element in the array

14

In [31]:
#n1[slice]
n1[1:4]#includes elements with in 2nd and last element

array([12, 13, 14])

In [32]:
#display first 2 elements of n1 using slicing 

In [33]:
n1[:2]

array([11, 12])

In [34]:
#n1[vector]

In [35]:
n1[[0,2,3]]

array([11, 13, 14])

#2D array
1.index
2.slicing
3.vector

In [36]:
l1=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [37]:
n44=np.array(l1)

In [38]:
n44

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
n44[0] #shows the 1st row

array([1, 2, 3, 4])

In [40]:
n44[-1] #shows the last row

array([13, 14, 15, 16])

In [ ]:
n44[3,3] #3rd row and 3rd column

In [42]:
n44[2,3] #2ndd row and 3rd column

12

In [47]:
l=[[10,20],[30,40],[50,60]]

In [53]:
s1=np.array(l)
s1

array([[10, 20],
       [30, 40],
       [50, 60]])

In [58]:
s1[0,0]

10

In [56]:
s1.shape

(3, 2)

In [60]:
s1[-1,-1]

60