In [1]:
import numpy as np

In [2]:
n2=np.random.randint(100,size=(6,4))

In [3]:
n2

array([[65, 89, 19, 30],
       [37, 60, 50,  8],
       [89, 32, 47, 57],
       [ 5, 44, 41, 65],
       [82, 26, 10, 70],
       [32, 73,  8,  2]])

In [5]:
#predefined fns
#eye
#create 2 matrix
#n34a--1,8 size 3,3
#n34b--5,13 size 3,4

In [16]:
n34a=np.random.randint(1,8,size=(3,3))
n34b=np.random.randint(5,13,,size=(3,3))

In [17]:
n34a

array([[5, 1, 1],
       [5, 6, 5],
       [2, 3, 2]])

In [18]:
n34b

array([[10,  5,  8],
       [ 5,  5,  5],
       [12,  9,  9]])

In [20]:
n34a.dot(n34b)

array([[ 67,  39,  54],
       [140, 100, 115],
       [ 59,  43,  49]])

In [21]:
np.mean(n34a)

3.3333333333333335

In [22]:
np.sum(n1,axis=0)

array([14, 15,  7])

In [23]:
np.sum(n34a)

30

In [24]:
np.amin(n34a)

1

In [25]:
n3=n34a+n34b
n3

array([[15,  6,  9],
       [10, 11, 10],
       [14, 12, 11]])

In [26]:
# write a python code to multiply a matrix of 2x3 by 21
#create an identity matrix of 4D by 4


In [27]:
n2=np.random.randint(23,size=(2,3))
n2

array([[10,  1, 12],
       [18,  2,  8]])

In [28]:
n2.dot(21)

array([[210,  21, 252],
       [378,  42, 168]])

In [29]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.shape(n2)

(2, 3)

In [45]:
n6=np.random.randint(10,size=(4,4))
n6

array([[1, 5, 0, 9],
       [9, 4, 9, 9],
       [3, 7, 4, 4],
       [7, 0, 9, 0]])

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.eye(6,k=0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [51]:
np.eye(4,k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])